"""generate_tests.py — user-facing entry point: give it one Python file and a
plain-English description of what the code does; get back a validated pytest
file that kills real injected bugs in that code.

    python generate_tests.py --file path/to/mymodule.py \
        --description "Parses ISO dates and computes business-day offsets" \
        --limit 15

Ties into the existing architecture rather than duplicating it:
  scaffolding   -> subjects/user_<name>/ with an auto bootstrap test (the
                   survival filter needs SOME existing suite to define
                   "surviving mutant"; an import-smoke test is the honest
                   minimum for user code with no tests)
  mutants       -> module1 (SDL + semantic + HOM; mutmut optional via flag)
  context       -> module2 index/retrieval; the user's description is always
                   injected as the first context chunk, so the model knows
                   intent, not just syntax
  generation    -> module3 templates + the agentic one-retry loop
  validation    -> validation_agent (pass-on-original AND fail-on-mutant)
  curation      -> only KILLED tests are merged into the output file; each is
                   provably a real regression test, not plausible-looking noise

Programmatic use (frontend: call this, poll the returned report):
    from generate_tests import generate_tests_for_file
    report = generate_tests_for_file("mymodule.py", "what it does", limit=15)
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import time
from pathlib import Path

from core.config import load_config
from core.guards import assert_not_windows_mount

PROJECT_ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = PROJECT_ROOT / "generated_test_suites"


def _slug(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)


def scaffold_subject(cfg: dict, file_path: Path, description: str) -> str:
    """Create subjects/user_<module>/ containing the user's file, a bootstrap
    test, and the description; register it in the in-memory config. Returns
    the subject key. Does NOT touch config.yaml on disk."""
    module_name = _slug(file_path.stem)
    key = f"user_{module_name}"
    subj_dir = PROJECT_ROOT / "subjects" / key
    if subj_dir.exists():
        shutil.rmtree(subj_dir)
    subj_dir.mkdir(parents=True)
    shutil.copy(file_path, subj_dir / f"{module_name}.py")
    # Bootstrap suite: must PASS on the original code (import smoke). This is
    # the minimum honest baseline — with no existing tests at all, "surviving
    # mutant" would be undefined and the survival filter would discard
    # everything as killed (pytest's no-tests-collected exit is nonzero).
    (subj_dir / "test_bootstrap.py").write_text(
        f"def test_import():\n    import {module_name}  # noqa: F401\n",
        encoding="utf-8")
    (subj_dir / "DESCRIPTION.md").write_text(description + "\n",
                                             encoding="utf-8")
    cfg["subjects"][key] = {
        "url": "", "path": f"subjects/{key}", "subdir": "",
        "test_selection": ["test_bootstrap.py"], "pytest_extra_args": [],
        "pin_commit": "", "user_description": description,
    }
    return key


def _description_chunk(description: str, module_file: str) -> dict:
    return {"document": f"User-provided description of this code:\n{description}",
            "metadata": {"file": module_file, "qualname": "(description)",
                         "kind": "description"}}


def _merge_tests(kept: list[tuple[str, str]], module_name: str) -> str:
    """Concatenate killing tests into one file, uniquifying test names."""
    parts = [f'"""Auto-generated regression tests for {module_name}.\n\n'
             "Every test below was validated: it PASSES on the original code\n"
             "and FAILS on a specific injected bug (the mutant named in the\n"
             'header comment). Generated by CodeKong."""\n']
    for i, (mutant_id, code) in enumerate(kept):
        code = re.sub(r"\bdef test_(\w+)\(",
                      lambda m: f"def test_{m.group(1)}_m{i}(", code)
        parts.append(f"\n# --- kills mutant: {mutant_id} ---\n{code.strip()}\n")
    return "\n".join(parts)


def generate_tests_for_file(file_path: str | Path, description: str,
                            k: int | None = None, limit: int | None = None,
                            use_mutmut: bool = False, use_rag: bool = True,
                            skip_semantic: bool = False,
                            cfg: dict | None = None, client=None,
                            progress=None, on_event=None) -> dict:
    """Full pipeline for one user file. Returns a JSON-serializable report.

    progress: optional callable(stage:int, detail:str) — purely additive UI
    hook (stages 0..4: scaffold, mutate+filter, index, generate+validate,
    package). Never affects pipeline behavior; failures in it are swallowed.

    on_event: optional callable(kind:str, payload:dict) — additive rich event
    stream carrying the REAL artifacts of each step (functions found, mutant
    diffs, retrieved chunks, validation verdicts) so a UI can show the whole
    process transparently. Same guarantees: no behavior change, failures
    swallowed. Kinds: scaffold, mutants, indexed, retrieve, result, done.
    """
    def _p(stage: int, detail: str = ""):
        if progress is not None:
            try:
                progress(stage, detail)
            except Exception:
                pass

    def _e(kind: str, **payload):
        if on_event is not None:
            try:
                on_event(kind, payload)
            except Exception:
                pass

    t0 = time.time()
    file_path = Path(file_path).resolve()
    if not file_path.is_file() or file_path.suffix != ".py":
        raise FileNotFoundError(f"{file_path} is not a Python file")

    cfg = cfg or load_config()
    assert_not_windows_mount(cfg["_project_root"])
    _p(0, "scaffolding subject")
    key = scaffold_subject(cfg, file_path, description)
    module_file = f"{_slug(file_path.stem)}.py"
    from core.srcmap import extract_functions
    subj_dir = Path(cfg["_project_root"]) / cfg["subjects"][key]["path"]
    _e("scaffold", module=module_file, description=description,
       functions=[{"name": fi.qualname, "lines": fi.end_lineno - fi.lineno + 1,
                   "source": fi.source[:600]}
                  for fi in extract_functions(subj_dir) if not fi.is_test])

    if client is None:
        from module3_llm.ollama_client import OllamaClient
        client = OllamaClient(cfg)

    # 1. Mutants. Written to an ISOLATED per-upload file — never the shared
    # module1_mutation/surviving_mutants.json, which belongs to the research
    # experiment and must not be clobbered by ad-hoc user uploads.
    from module1_mutation.mutant_normalizer import build_surviving_mutants
    OUTPUT_DIR.mkdir(exist_ok=True)
    mutants_path = OUTPUT_DIR / f"mutants_{key}.json"
    _p(1, "injecting mutants and filtering survivors")
    mutants = build_surviving_mutants(cfg, key, client, mutants_path,
                                      skip_mutmut=not use_mutmut,
                                      skip_semantic=skip_semantic)
    if limit:
        mutants = mutants[:limit]
    _e("mutants", mutants=[{"id": m["mutant_id"],
                            "mutation_class": m["mutation_class"],
                            "description": m["mutation_description"][:300],
                            "diff": m["diff"][:1500]} for m in mutants])

    # 2. Context. Description chunk always leads; RAG adds retrieved chunks.
    retriever = None
    if use_rag and mutants:
        _p(2, "indexing repository into ChromaDB")
        from agentic import knowledge_agent
        from module2_rag.retriever import Retriever
        import json as _json
        manifest_path = knowledge_agent.run(cfg, key)
        n_chunks = _json.loads(manifest_path.read_text(
            encoding="utf-8")).get(key, {}).get("chunks")
        _e("indexed", chunks=n_chunks,
           embedding_model=cfg["rag"]["embedding_model"])
        retriever = Retriever(cfg, key)
    k = k or cfg["rag"]["default_k"]

    # 3. Generate + validate through the agentic loop; curate kills.
    from agentic.test_gen_agent import generate_and_validate
    records, kept = [], []
    for i, m in enumerate(mutants):
        _p(3, f"mutant {i + 1}/{len(mutants)}: {m['mutant_id']}")
        chunks = [_description_chunk(description, module_file)]
        if retriever is not None:
            chunks += retriever.retrieve(m, k)
        _e("retrieve", mutant_id=m["mutant_id"], k=k,
           chunks=[{"file": c.get("metadata", {}).get("file"),
                    "qualname": c.get("metadata", {}).get("qualname"),
                    "kind": c.get("metadata", {}).get("kind"),
                    "distance": c.get("distance"),
                    "snippet": (c.get("document") or "")[:300]}
                   for c in chunks])
        rec = generate_and_validate(cfg, key, m, chunks, "RAG", client, k=k)
        records.append(rec)
        print(f"[usercode] {m['mutant_id']}: {rec['status']}")
        test_code = None
        if rec["status"] == "KILLED" and rec.get("test_file"):
            test_code = Path(rec["test_file"]).read_text(encoding="utf-8")
            kept.append((m["mutant_id"], test_code))
        _e("result", mutant_id=m["mutant_id"], status=rec["status"],
           attempts=rec["attempts"], retry_used=rec["retry_used"],
           validations=[{"attempt": v.get("attempt"), "status": v.get("status"),
                         "stage": v.get("stage"),
                         "reason": (v.get("reason") or "")[:300]}
                        for v in rec.get("validation", [])],
           test_code=(test_code or "")[:1500] or None)

    # 4. Output artifacts.
    _p(4, "curating killed tests and packaging")
    OUTPUT_DIR.mkdir(exist_ok=True)
    out_tests = OUTPUT_DIR / f"test_{_slug(file_path.stem)}_generated.py"
    if kept:
        out_tests.write_text(_merge_tests(kept, file_path.stem),
                             encoding="utf-8")
    report = {
        "input_file": str(file_path), "description": description,
        "subject_key": key, "mutants_attempted": len(mutants),
        "mutants_killed": len(kept),
        "kill_rate": round(len(kept) / len(mutants), 3) if mutants else None,
        "statuses": {s: sum(1 for r in records if r["status"] == s)
                     for s in {r["status"] for r in records}},
        "output_test_file": str(out_tests) if kept else None,
        "records": records, "wall_seconds": round(time.time() - t0, 1),
        "model": cfg["llm"]["model"], "used_rag": use_rag, "k": k,
    }
    report_path = OUTPUT_DIR / f"report_{_slug(file_path.stem)}.json"
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    _e("done", mutants_attempted=report["mutants_attempted"],
       mutants_killed=report["mutants_killed"],
       kill_rate=report["kill_rate"], wall_seconds=report["wall_seconds"],
       statuses=report["statuses"],
       output_test_file=report["output_test_file"])
    print(f"[usercode] killed {len(kept)}/{len(mutants)} mutants; "
          f"tests -> {out_tests if kept else '(none kept)'}; "
          f"report -> {report_path}")
    return report


def main():
    ap = argparse.ArgumentParser(
        description="Generate validated tests for a single Python file")
    ap.add_argument("--file", required=True, help="path to the .py file")
    ap.add_argument("--description", required=True,
                    help="plain-English summary of what the code does")
    ap.add_argument("--limit", type=int, default=None,
                    help="cap number of mutants (start small: 10-20)")
    ap.add_argument("--k", type=int, default=None)
    ap.add_argument("--use-mutmut", action="store_true",
                    help="also run mutmut for syntactic mutants (slower)")
    ap.add_argument("--no-rag", action="store_true",
                    help="skip repo retrieval (description is still injected)")
    ap.add_argument("--skip-semantic", action="store_true",
                    help="skip LLM-generated semantic mutants (faster)")
    args = ap.parse_args()
    generate_tests_for_file(args.file, args.description, k=args.k,
                            limit=args.limit, use_mutmut=args.use_mutmut,
                            use_rag=not args.no_rag,
                            skip_semantic=args.skip_semantic)


if __name__ == "__main__":
    main()
